### ISSUE TITLE
what is dimensions and criteria?

### ISSUE THREAD

**Issue by safavie** [PotyZed/DANP#3]
Hello
For this example you have given, what is the value of the following parameters?

how many dimensions does your research have?
how many criteria does your 1st dimension contain?

**Comment by PotyZed** [comment]
Hello there
There are 7 dimensions and each contains 2, 1, 1, 1, 1, 3, and 1 criteria respectively. For example, the first dimension contains 2 criteria and the sixth dimension contains 3 criteria.
Hope that was helpful.

**Comment by safavie** [comment]
Can you explain more?
Thank you
